# Copyright 2025 IT-Stecher
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import fields, models, api, _
from odoo.exceptions import ValidationError, UserError
import logging
from datetime import datetime, date, timedelta

_logger = logging.getLogger(__name__)


class PmsProperty(models.Model):
    _inherit = "pms.property"

    # --- Italian Guest Registration Configuration ---
    it_guest_registration_enabled = fields.Boolean(
        string="Enable Italian Guest Registration",
        help="Enable automatic guest registration with Italian Police (Alloggiati Web)"
    )

    # --- Alloggiati Web Configuration ---
    alloggiati_web_url = fields.Char(
        string="Alloggiati Web URL",
        help="URL for the Alloggiati Web service",
        default="https://alloggiatiweb.poliziadistato.it/service/",
    )
    alloggiati_web_username = fields.Char(
        string="Username",
        help="Username for Alloggiati Web service"
    )
    alloggiati_web_password = fields.Char(
        string="Password",
        help="Password for Alloggiati Web service"
    )
    alloggiati_web_wskey = fields.Char(
        string="WS Key",
        help="Web Service Key generated by Alloggiati Web interface"
    )
    alloggiati_web_codice_struttura = fields.Char(
        string="Codice Struttura",
        help="Structure code assigned by Police (Questura)"
    )
    alloggiati_web_codice_categoria = fields.Selection([
        ('1', 'Albergo'),
        ('2', 'Villaggio Turistico'),
        ('3', 'Campeggio'),
        ('4', 'Alloggio Agrituristico'),
        ('5', 'Bed & Breakfast'),
        ('6', 'Residence'),
        ('7', 'Casa Vacanza'),
        ('8', 'Affittacamere'),
        ('9', 'Ostello'),
        ('10', 'Casa per Ferie'),
        ('11', 'Altro'),
    ], string="Categoria Struttura", help="Category of the accommodation structure")
    alloggiati_web_test_mode = fields.Boolean(
        string="Test Mode",
        default=True,
        help="Enable test mode for Alloggiati Web (uses test environment)"
    )

    # --- Automatic registration settings ---
    auto_register_checkin = fields.Boolean(
        string="Auto Register on Check-in",
        default=False,
        help="Automatically register guests when they check in"
    )
    auto_register_time = fields.Char(
        string="Auto Register Time",
        default="23:00",
        help="Time of day to automatically register guests (HH:MM format)"
    )
    last_registration_date = fields.Datetime(
        string="Last Registration Date",
        readonly=True,
        help="Date and time of the last guest registration"
    )
    registration_count = fields.Integer(
        string="Total Registrations",
        default=0,
        readonly=True,
        help="Total number of guest registrations sent"
    )

    # --- Auto-selection configuration ---
    auto_select_guests = fields.Boolean(
        string="Auto-select Guests for Registration",
        default=True,
        help="Automatically select new guests for registration"
    )
    auto_select_criteria = fields.Selection([
        ('all', 'All Guests'),
        ('adults_only', 'Adults Only (18+)'),
        ('non_exempt', 'Non-exempt Guests Only'),
        ('by_nationality', 'By Nationality'),
    ], string="Auto-selection Criteria", default='non_exempt')
    auto_select_nationalities = fields.Many2many(
        'res.country',
        string="Auto-select Nationalities",
        help="Only auto-select guests from these countries (if criteria is 'by_nationality')"
    )
    auto_register_delay_hours = fields.Integer(
        string="Auto-register Delay (hours)",
        default=0,
        help="Wait this many hours after check-in before auto-registering"
    )
    exempt_minors_under_age = fields.Integer(
        string="Exempt Minors Under Age",
        default=14,
        help="Automatically exempt guests under this age"
    )

    # --- Remote Check-in Configuration ---
    remote_checkin_enabled = fields.Boolean(
        string="Enable Remote Check-in",
        default=False,
        help="Allow guests to complete check-in remotely via email link"
    )
    remote_checkin_hours_before = fields.Integer(
        string="Remote Check-in Available (hours before)",
        default=48,
        help="How many hours before arrival guests can start remote check-in"
    )
    remote_checkin_reminder_hours = fields.Integer(
        string="Send Reminder (hours before)",
        default=24,
        help="Send reminder email this many hours before arrival"
    )

    # --- Receipt Download Configuration ---
    auto_download_receipts = fields.Boolean(
        string="Auto Download Receipts",
        default=True,
        help="Automatically download receipts from Alloggiati Web"
    )
    receipt_retention_days = fields.Integer(
        string="Receipt Retention (days)",
        default=730,  # 2 years
        help="How long to keep downloaded receipts"
    )

    # --- Enhanced notification settings ---
    registration_notification_emails = fields.Char(
        string="Notification Emails",
        help="Comma-separated email addresses for registration notifications"
    )
    send_success_notifications = fields.Boolean(
        string="Send Success Notifications",
        default=False,
        help="Send email notifications for successful registrations"
    )
    send_error_notifications = fields.Boolean(
        string="Send Error Notifications",
        default=True,
        help="Send email notifications for failed registrations"
    )

    # --- Advanced settings ---
    validate_guest_data = fields.Boolean(
        string="Validate Guest Data",
        default=True,
        help="Perform enhanced validation of guest data before sending"
    )
    allow_partial_registrations = fields.Boolean(
        string="Allow Partial Registrations",
        default=True,
        help="Allow registration even if some guests have invalid data"
    )
    max_registration_retries = fields.Integer(
        string="Max Registration Retries",
        default=3,
        help="Maximum number of retry attempts for failed registrations"
    )

    # --- Statistics and monitoring ---
    total_guests_registered = fields.Integer(
        string="Total Guests Registered",
        compute="_compute_registration_stats",
        store=True
    )
    last_successful_registration = fields.Datetime(
        string="Last Successful Registration",
        compute="_compute_registration_stats",
        store=True
    )
    failed_registrations_count = fields.Integer(
        string="Failed Registrations",
        compute="_compute_registration_stats",
        store=True
    )

    @api.constrains('auto_register_time')
    def _check_auto_register_time(self):
        """Validate time format"""
        for record in self:
            if record.auto_register_time:
                import re
                time_pattern = r'^([01]?[0-9]|2[0-3]):[0-5][0-9]$'
                if not re.match(time_pattern, record.auto_register_time):
                    raise ValidationError(_("Invalid time format. Please use HH:MM format (e.g., 23:00)"))


    @api.depends('registration_count')
    def _compute_registration_stats(self):
        for record in self:
            successful_registrations = self.env['pms.guest.registration'].search([
                ('property_id', '=', record.id),
                ('state', '=', 'sent')
            ])
            record.total_guests_registered = sum(successful_registrations.mapped('guest_count'))
            record.last_successful_registration = max(
                successful_registrations.mapped('transmission_date'),
                default=False
            )
            failed_registrations = self.env['pms.guest.registration'].search_count([
                ('property_id', '=', record.id),
                ('state', '=', 'error')
            ])
            record.failed_registrations_count = failed_registrations

    @api.model
    def get_guests_for_auto_registration(self, date_from=None, date_to=None):
        self.ensure_one()
        if not date_from:
            date_from = fields.Date.today()
        if not date_to:
            date_to = date_from
        domain = [
            ('arrival', '>=', date_from),
            ('arrival', '<=', date_to),
            ('state', '=', 'onboard'),
            ('it_registered', '=', False),
        ]
        if 'pms_property_id' in self.env['pms.checkin.partner']._fields:
            domain.append(('pms_property_id', '=', self.id))
        elif 'property_id' in self.env['pms.checkin.partner']._fields:
            domain.append(('property_id', '=', self.id))
        else:
            reservations = self.env['pms.reservation'].search([
                ('pms_property_id', '=', self.id),
                ('state', 'in', ['onboard', 'confirm']),
            ])
            domain.append(('reservation_id', 'in', reservations.ids))
        if self.auto_select_criteria == 'adults_only':
            min_birthdate = fields.Date.today() - timedelta(days=18*365.25)
            domain.append(('birthdate_date', '<=', min_birthdate))
        elif self.auto_select_criteria == 'non_exempt':
            domain.append(('it_exemption_reason', '=', False))
        elif self.auto_select_criteria == 'by_nationality':
            if self.auto_select_nationalities:
                domain.append(('nationality_id', 'in', self.auto_select_nationalities.ids))
        if self.auto_register_delay_hours > 0:
            delay_datetime = fields.Datetime.now() - timedelta(hours=self.auto_register_delay_hours)
            domain.append(('checkin', '<=', delay_datetime))
        return self.env['pms.checkin.partner'].search(domain)

    @api.constrains('alloggiati_web_username', 'alloggiati_web_password', 'alloggiati_web_codice_struttura', 'alloggiati_web_wskey')
    def _check_alloggiati_web_config(self):
        for record in self:
            if record.it_guest_registration_enabled:
                if not record.alloggiati_web_username:
                    raise ValidationError(_("Username is required for Alloggiati Web"))
                if not record.alloggiati_web_password:
                    raise ValidationError(_("Password is required for Alloggiati Web"))
                if not record.alloggiati_web_codice_struttura:
                    raise ValidationError(_("Codice Struttura is required for Alloggiati Web"))
                if not record.alloggiati_web_wskey:
                    raise ValidationError(_("WS Key is required for Alloggiati Web"))

    @api.constrains('remote_checkin_hours_before', 'remote_checkin_reminder_hours')
    def _check_remote_checkin_timing(self):
        for record in self:
            if record.remote_checkin_enabled:
                if record.remote_checkin_hours_before < 1:
                    raise ValidationError(_("Remote check-in must be available at least 1 hour before arrival"))
                if record.remote_checkin_reminder_hours > record.remote_checkin_hours_before:
                    raise ValidationError(_("Reminder cannot be sent after remote check-in becomes available"))

    def test_alloggiati_web_connection(self):
        self.ensure_one()
        try:
            from . import pms_guest_registration
            test_registration = self.env['pms.guest.registration'].new({
                'property_id': self.id,
                'registration_date': fields.Date.today(),
            })
            token_info = test_registration._get_authentication_token()
            if token_info.get('success'):
                return {
                    'type': 'ir.actions.client',
                    'tag': 'display_notification',
                    'params': {
                        'title': _('Connection Test'),
                        'message': _('Connection test successful! Authentication token received.'),
                        'type': 'success',
                    }
                }
            else:
                return {
                    'type': 'ir.actions.client',
                    'tag': 'display_notification',
                    'params': {
                        'title': _('Connection Test'),
                        'message': _('Connection test failed: %s') % token_info.get('error', 'Unknown error'),
                        'type': 'danger',
                    }
                }
        except Exception as e:
            _logger.error("Alloggiati Web connection test failed: %s", str(e))
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Connection Test'),
                    'message': _('Connection test failed: %s') % str(e),
                    'type': 'danger',
                }
            }

    def action_test_alloggiati_connection_enhanced(self):
        self.ensure_one()
        try:
            temp_registration = self.env['pms.guest.registration'].new({
                'property_id': self.id,
                'registration_date': fields.Date.today(),
            })
            token_info = temp_registration._get_authentication_token()
            if not token_info.get('success'):
                return {
                    'type': 'ir.actions.client',
                    'tag': 'display_notification',
                    'params': {
                        'title': _('Connection Test Failed'),
                        'message': _('Authentication failed: %s') % token_info.get('error', 'Unknown error'),
                        'type': 'danger',
                    }
                }
            test_schedina = "16" + "01/01/2024" + "01" + "TEST".ljust(50) + "GUEST".ljust(30) + "1" + \
                          "01/01/1990" + "000000000" + "  " + "100000001" + "100000001" + \
                          "1".ljust(5) + "TEST123".ljust(20) + "100000001"
            test_schedina = test_schedina.ljust(168)
            test_result = temp_registration._test_schedine([test_schedina])
            if test_result.get('success'):
                return {
                    'type': 'ir.actions.client',
                    'tag': 'display_notification',
                    'params': {
                        'title': _('Connection Test Successful'),
                        'message': _('Authentication and data format validation successful!'),
                        'type': 'success',
                    }
                }
            else:
                return {
                    'type': 'ir.actions.client',
                    'tag': 'display_notification',
                    'params': {
                        'title': _('Connection Test Partial'),
                        'message': _('Authentication OK, but test data failed: %s') % test_result.get('error', ''),
                        'type': 'warning',
                    }
                }
        except Exception as e:
            _logger.error("Enhanced connection test failed: %s", str(e))
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Connection Test Error'),
                    'message': _('Test failed with error: %s') % str(e),
                    'type': 'danger',
                }
            }

    def action_send_remote_checkin_links(self):
        self.ensure_one()
        if not self.remote_checkin_enabled:
            raise UserError(_("Remote check-in is not enabled for this property"))
        arrival_window_start = fields.Datetime.now()
        arrival_window_end = arrival_window_start + timedelta(hours=self.remote_checkin_hours_before)
        reservations = self.env['pms.reservation'].search([
            ('pms_property_id', '=', self.id),
            ('checkin', '>=', arrival_window_start),
            ('checkin', '<=', arrival_window_end),
            ('state', 'in', ['confirm', 'onboard'])
        ])
        sent_count = 0
        for reservation in reservations:
            if reservation.partner_id and reservation.partner_id.email:
                try:
                    existing_token = self.env['pms.remote.checkin.token'].search([
                        ('reservation_id', '=', reservation.id),
                        ('state', 'in', ['sent', 'accessed']),
                        ('expires_at', '>', fields.Datetime.now())
                    ])
                    if not existing_token:
                        token = self.env['pms.remote.checkin.token'].generate_token_for_reservation(
                            reservation.id,
                            reservation.partner_id.email
                        )
                        sent_count += 1
                except Exception as e:
                    _logger.error(
                        "Failed to send remote check-in link for reservation %s: %s",
                        reservation.name, str(e)
                    )
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Remote Check-in Links Sent'),
                'message': _('%d remote check-in links sent successfully') % sent_count,
                'type': 'success',
            }
        }

    def action_cleanup_old_receipts(self):
        self.ensure_one()
        if self.receipt_retention_days <= 0:
            return
        cutoff_date = fields.Date.today() - timedelta(days=self.receipt_retention_days)
        old_receipts = self.env['pms.guest.registration.receipt'].search([
            ('property_id', '=', self.id),
            ('receipt_date', '<', cutoff_date)
        ])
        deleted_count = len(old_receipts)
        old_receipts.unlink()
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Cleanup Complete'),
                'message': _('%d old receipts deleted') % deleted_count,
                'type': 'info',
            }
        }

    def action_view_registration_dashboard(self):
        return {
            'type': 'ir.actions.act_window',
            'name': _('Registration Dashboard'),
            'res_model': 'pms.guest.registration.dashboard',
            'view_mode': 'graph,tree',
            'domain': [('property_id', '=', self.id)],
            'context': {
                'search_default_group_date': 1,
                'search_default_this_month': 1,
            }
        }

    def action_view_receipts(self):
        return {
            'type': 'ir.actions.act_window',
            'name': _('Registration Receipts'),
            'res_model': 'pms.guest.registration.receipt',
            'view_mode': 'tree,form',
            'domain': [('property_id', '=', self.id)],
            'context': {
                'search_default_this_month': 1,
            }
        }

    def action_view_remote_checkins(self):
        return {
            'type': 'ir.actions.act_window',
            'name': _('Remote Check-ins'),
            'res_model': 'pms.remote.checkin.token',
            'view_mode': 'tree,form',
            'domain': [('property_id', '=', self.id)],
            'context': {
                'search_default_active': 1,
            }
        }

    def action_open_table_manager(self):
        self.ensure_one()
        table_manager = self.env['alloggiati.table.manager'].search([
            ('property_id', '=', self.id)
        ], limit=1)
        if not table_manager:
            table_manager = self.env['alloggiati.table.manager'].create({
                'property_id': self.id
            })
        return {
            'type': 'ir.actions.act_window',
            'name': _('Table Manager'),
            'res_model': 'alloggiati.table.manager',
            'view_mode': 'form',
            'res_id': table_manager.id,
            'target': 'current',
        }

    def action_sync_tables(self):
        self.ensure_one()
        table_manager = self.env['alloggiati.table.manager'].search([
            ('property_id', '=', self.id)
        ], limit=1)
        if not table_manager:
            table_manager = self.env['alloggiati.table.manager'].create({
                'property_id': self.id
            })
        return table_manager.action_sync_all_tables()

    def _send_registration_notification(self, property_rec, registration, registered_count, exempted_count):
        template = self.env.ref('pms_l10n_it.email_template_registration_notification', False)
        if template:
            template.with_context(
                registered_count=registered_count,
                exempted_count=exempted_count,
                property_name=property_rec.name,
                registration_id=registration.id
            ).send_mail(property_rec.id)

    @api.model
    def _cron_auto_guest_registration(self):
        properties = self.search([
            ('it_guest_registration_enabled', '=', True),
            ('auto_register_checkin', '=', True)
        ])
        current_time = fields.Datetime.now()
        current_hour_minute = current_time.strftime('%H:%M')
        for property_rec in properties:
            try:
                target_time = property_rec.auto_register_time
                if target_time and current_hour_minute == target_time:
                    guests_to_register = property_rec.get_guests_for_auto_registration()
                    if guests_to_register:
                        exempted_guests = self.env['pms.checkin.partner']
                        for guest in guests_to_register:
                            if guest.birthdate_date:
                                age = (fields.Date.today() - guest.birthdate_date).days / 365.25
                                if age < property_rec.exempt_minors_under_age:
                                    guest.write({
                                        'it_exemption_reason': 'minor',
                                        'it_exemption_notes': _('Auto-exempted: Minor under %s years') % property_rec.exempt_minors_under_age
                                    })
                                    exempted_guests |= guest
                        guests_to_register -= exempted_guests
                        if guests_to_register:
                            registration = self.env['pms.guest.registration'].create({
                                'property_id': property_rec.id,
                                'registration_date': fields.Date.today(),
                                'checkin_partner_ids': [(6, 0, guests_to_register.ids)],
                            })
                            try:
                                registration.action_send_registration()
                                _logger.info(
                                    "Auto-registration successful for property %s: %d guests registered, %d exempted",
                                    property_rec.name,
                                    len(guests_to_register),
                                    len(exempted_guests)
                                )
                                if property_rec.registration_notification_emails:
                                    self._send_registration_notification(
                                        property_rec,
                                        registration,
                                        len(guests_to_register),
                                        len(exempted_guests)
                                    )
                            except Exception as e:
                                _logger.error(
                                    "Auto-registration failed for property %s: %s",
                                    property_rec.name, str(e)
                                )
                                registration.write({
                                    'state': 'error',
                                    'error_message': str(e)
                                })
            except Exception as e:
                _logger.error(
                    "Error in auto-registration cron for property %s: %s",
                    property_rec.name, str(e)
                )

    @api.model
    def _cron_send_remote_checkin_reminders(self):
        properties = self.search([
            ('remote_checkin_enabled', '=', True),
            ('remote_checkin_reminder_hours', '>', 0)
        ])
        for property_rec in properties:
            try:
                reminder_time = fields.Datetime.now() + timedelta(hours=property_rec.remote_checkin_reminder_hours)
                tokens = self.env['pms.remote.checkin.token'].search([
                    ('property_id', '=', property_rec.id),
                    ('state', '=', 'sent'),
                    ('reservation_id.checkin', '<=', reminder_time),
                    ('expires_at', '>', fields.Datetime.now())
                ])
                for token in tokens:
                    if not hasattr(token, 'reminder_sent') or not token.reminder_sent:
                        token._send_reminder_email()
            except Exception as e:
                _logger.error(
                    "Error sending remote check-in reminders for property %s: %s",
                    property_rec.name, str(e)
                )

    @api.model
    def _cron_cleanup_old_data(self):
        properties = self.search([('it_guest_registration_enabled', '=', True)])
        for property_rec in properties:
            try:
                if property_rec.auto_download_receipts and property_rec.receipt_retention_days > 0:
                    property_rec.action_cleanup_old_receipts()
                expired_tokens = self.env['pms.remote.checkin.token'].search([
                    ('property_id', '=', property_rec.id),
                    ('expires_at', '<', fields.Datetime.now()),
                    ('state', '!=', 'expired')
                ])
                expired_tokens.write({'state': 'expired'})
                old_checkin_data = self.env['pms.remote.checkin.data'].search([
                    ('token_id.property_id', '=', property_rec.id),
                    ('create_date', '<', fields.Datetime.now() - timedelta(days=365))
                ])
                old_checkin_data.unlink()
            except Exception as e:
                _logger.error(
                    "Error cleaning up old data for property %s: %s",
                    property_rec.name, str(e)
                )